import turtle

for i in range(1):
    turtle.shapesize(0.01)
    turtle.pensize(5)
    turtle.pencolor("blue")
    turtle.title("Animation 1")
    turtle.speed(1)
    turtle.left(270)
    turtle.forward(90)
    turtle.left(90)
    turtle.forward(90)
    turtle.clear()
    turtle.penup()
    turtle.goto(0,0)
    turtle.pendown()
    turtle.left(270)
    turtle.forward(90)
    turtle.penup()
    turtle.goto(0,0)
    turtle.goto(0,90)
    turtle.pendown()
    turtle.forward(9)
    turtle.clear()
    turtle.penup()
    turtle.goto(0,0)
    turtle.pendown()
    turtle.left(45)
    turtle.forward(90)
    turtle.left(90)
    turtle.forward(90)
    turtle.penup()
    turtle.clear()
    turtle.goto(0,0)
    turtle.pendown()
    turtle.left(225)
    turtle.forward(90)
    turtle.penup()
    turtle.goto(0,90)
    turtle.pendown()
    turtle.forward(9)
    turtle.clear()
    turtle.penup()

    
turtle.exitonclick()
    