import turtle
turtle.title("Turtle's Adventures")
turtle.bgcolor("lightgray")
turtle.setposition(0,0)
turtle.setposition(20,0)
turtle.setposition(20,20)
turtle.setposition(40,20)
turtle.setposition(40,0)
turtle.setposition(60,0)
turtle.setposition(60,20)
turtle.setposition(120,20)
turtle.setposition(120,290)
turtle.penup()
turtle.setposition(0,-20)
turtle.pendown()
turtle.setposition(20,-20)
turtle.setposition(20,-10)
turtle.setposition(40,-10)
turtle.setposition(40,-20)
turtle.setposition(60,-20)
turtle.setposition(300,-20)
turtle.penup()
turtle.setposition(300,90)
turtle.setposition(150,90)
turtle.pendown()
turtle.setposition(150,20)
turtle.setposition(150,290)
turtle.penup()
turtle.setposition(150,150)
turtle.pendown()
turtle.setposition(310,150)
turtle.setposition(310,-20)
turtle.penup()
turtle.setposition(235,75)
turtle.pendown()
turtle.setposition(235,20)
turtle.penup()
turtle.setposition(120,290)
turtle.pendown()
turtle.setposition(150,290)
turtle.penup()
turtle.setposition(0,0)
turtle.pendown()
turtle.setposition(0,-20)
turtle.penup()
turtle.setposition(-300,0)
turtle.pendown()
turtle.setposition(-300,90)
turtle.setposition(-390,90)
turtle.setposition(-390,-100)
turtle.setposition(-300,-100)
turtle.setposition(-300,90)
turtle.pencolor("black")
turtle.penup()
turtle.setposition(200,-120)
turtle.pendown()
turtle.setposition(350,-120)
turtle.setposition(350,-210)
turtle.setposition(170,-210)
turtle.setposition(170,-120)
turtle.setposition(210,-120)
turtle.pencolor("black")
turtle.penup()
yellow_circles = [(135,270),(-340,-10)]
turtle.setposition(135,270)
turtle.pendown()
turtle.pencolor("yellow")
turtle.circle(5)
turtle.penup()
turtle.setposition(-340,-10)
turtle.pendown()
turtle.pencolor("yellow")                
turtle.circle(5)
turtle.penup()
purple_circles = [(-315,70),(260,-160)]
turtle.setposition(-310,70)
turtle.pendown()
turtle.pencolor("purple")
turtle.circle(5)
turtle.penup()
turtle.setposition(260,-160)
turtle.pendown()
turtle.pencolor("purple")
turtle.circle(5)
turtle.penup()
blue_circles = [(340,-140),(300,130)]
turtle.setposition(340,-140)
turtle.pendown()
turtle.pencolor("blue")
turtle.circle(5)
turtle.penup()
turtle.setposition(300,130)
turtle.pendown()
turtle.pencolor("blue")
turtle.circle(5)
turtle.pencolor("black")
turtle.penup()
turtle.setposition(12,-15)
turtle.pendown()
turtle.pencolor("red")
turtle.circle(5)


def p():
    x,y = turtle.position()
    if x > purple_circles[0][0]-5 and x < purple_circles[0][0]+5 and y > purple_circles[0][1]-5 and y < purple_circles[0][1]+5:
        turtle.setposition(purple_circles[1][0]+30,purple_circles[1][1])
def p2():
    x,y = turtle.position()
    if x > purple_circles[1][0]-5 and x < purple_circles[1][0]+5 and y > purple_circles[1][1]-5 and y < purple_circles[1][1]+5:
        turtle.setposition(purple_circles[0][0]-20,purple_circles[0][1])
def y():
    x,y = turtle.position()
    if x > yellow_circles[0][0]-5 and x < yellow_circles[0][0]+5 and y > yellow_circles[0][1]-5 and y < yellow_circles[0][1]+5:
        turtle.setposition(yellow_circles[1][0]-10, yellow_circles[1][1])
def y2():
    x,y = turtle.position()
    if x > yellow_circles[1][0]-5 and x < yellow_circles[1][0]+5 and y > yellow_circles[1][1]-5 and y < yellow_circles[0][1]+5:
        turtle.setposition(yellow_circles[0][0]-10, yellow_circles[0][1])
def b():
    x,y = turtle.position()
    if x > blue_circles[0][0]-5 and x < blue_circles[0][0]+5 and y > blue_circles[0][1]-5 and y < blue_circles [0][1]+5:
        turtle.setposition(blue_circles[1][0], blue_circles[1][1])
def b2():
    x,y = turtle.position()
    if x > blue_circles[1][0]-5 and x < blue_circles[1][0]+5 and y > blue_circles[1][1]-5 and y < blue_circles [0][1]+5:
        turtle.setpositon(blue_circles[0][0], blue_circles[0][1])
        



def move_up():
    turtle.setheading(90)
    turtle.forward(5)
    p()
    p2()
    y()
    y2()
    b()
    b2()
turtle.penup()
turtle.onkey(move_up,"Up")
turtle.listen()

def move_left():
    turtle.setheading(180)
    turtle.forward(5)
    p()
    p2()
    y()
    y2()
    b()
    b2()
turtle.penup()
turtle.onkey(move_left, "Left")
turtle.listen()

def move_down():
    turtle.setheading(-90)
    turtle.forward(5)
    p()
    p2()
    y()
    y2()
    b()
    b2()   
turtle.penup()
turtle.onkey(move_down, "Down")
turtle.listen()

def move_right():
    turtle.setheading(0)
    turtle.forward(5)
    p()
    p2()
    y()
    y2()
    b()
    b2()
turtle.penup()
turtle.onkey(move_right, "Right")
turtle.listen()
turtle.exitonclick()

